#!/bin/bash
#How to install Helm
#The installation of Helm is actually quite simple. Log in to your Kubernetes master and download the necessary .tar file with the command:

#wget https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
#If your architecture is not amd64, download the correct version from the Helm release page.

#Once the file is downloaded, unpack it with the command:

#tar xvf helm-v3.0.2-linux-amd64.tar.gz
#Finally move the executable to the proper location with the command:

#sudo mv linux-amd64/helm /usr/local/bin/
#To verify the install worked, issue the command:

#helm version


set -eou pipefail

#set helm version
helmVersion=helm-v3.0.2-linux-amd64.tar.gz

#download helm version
wget https://get.helm.sh/$helmVersion
tar xvzf $helmVersion

#mv helm3 binary to local tmp folder
if [[ -e /usr/local/bin/tmp ]] ; then echo "tmp folder already exists" ; else mkdir /usr/local/bin/tmp ; fi
mv darwin-amd64/helm /usr/local/bin/tmp/helm

#TEMPORARY export $HELM_HOME so you don't overwrite Helm2 ~/.helm/
export HELM_HOME=/usr/local/bin/tmp/helm3

#set temp alias
helm3=/usr/local/bin/tmp/helm

#add alias to .bashrc
echo "alias helm3=/usr/local/bin/tmp/helm" >> ~/.bashrc

# cleanup
rm -rf $helmVersion
rm -rf darwin-amd64
